//<auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Labels.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddUniqueLabelNameConstraint : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateIndex(
                name: "IX_Labels_BoardId_Name",
                schema: "label",
                table: "Labels",
                columns: new[] { "BoardId", "Name" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Labels_BoardId_Name",
                schema: "label",
                table: "Labels");
        }
    }
}
